language: rust
cache: cargo
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
script:
  - cargo build --manifest-path=harfbuzz-sys/Cargo.toml
  - cargo package --manifest-path=harfbuzz-sys/Cargo.toml
