language: rust
cache: cargo
env: PACKAGE=$TRAVIS_BUILD_DIR/target/package/harfbuzz-sys-0.3.2
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
script:
  - mkdir -p $PACKAGE
  - pushd $PACKAGE
  - git init
  - git add .
  - popd
  - cargo package --manifest-path=harfbuzz-sys/Cargo.toml
  - cd $PACKAGE
  - git diff
