language: rust
cache: cargo
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
    - os: linux
      rust: stable
script:
  - cargo package --manifest-path=harfbuzz-sys/Cargo.toml
  - cd $TRAVIS_BUILD_DIR/target/package/harfbuzz-sys-0.3.2
  - git diff
